removed spurious Latin-1 char in qwiic_kx13x.py
Was causing this error on Linux:

    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xa0 in position 173: invalid start byte